"""Starter US-warehouse dropship catalog.

Every entry ships from a US warehouse (2-7 day domestic delivery — the
whole point vs. AliExpress-style 3-week shipping). Supplier names are real
US dropship supplier programs (Sunrise Wholesale, GreenDropShip, BryBelly,
Pet Stores USA, US Direct Wholesale) so the catalog reads like what a real
feed will return when a supplier API is wired in.

Rows are upserted by ``sku`` — a real feed can update cost/stock without
duplicating. ``niche`` keys match ``niche_service.NICHES`` so a user's
subscribed niches drive curation 1:1.
"""

CATALOG: list[dict] = [
    # ── Electronics ─────────────────────────────────────────────────────
    dict(sku="ELEC-001", niche="electronics", supplier="Sunrise Wholesale", warehouse_state="CA",
         title="MagSafe-Compatible 3-in-1 Charging Station",
         description="Foldable magnetic charging dock for phone, watch and earbuds. 15W fast charge, travel-friendly.",
         cost=11.50, suggested_price=34.99, shipping_days_min=2, shipping_days_max=5, trending_score=88),
    dict(sku="ELEC-002", niche="electronics", supplier="Sunrise Wholesale", warehouse_state="CA",
         title="Smart WiFi LED Light Strip — 32ft, App + Voice Control",
         description="RGBIC strip, Alexa/Google compatible, music sync. Perennial best-seller in smart home.",
         cost=8.20, suggested_price=27.99, shipping_days_min=2, shipping_days_max=5, trending_score=91),
    dict(sku="ELEC-003", niche="electronics", supplier="US Direct Wholesale", warehouse_state="TX",
         title="Bluetooth Sleep Headband Headphones",
         description="Ultra-thin speakers in a washable headband — side-sleeper friendly. Strong TikTok traction.",
         cost=6.40, suggested_price=24.99, shipping_days_min=3, shipping_days_max=6, trending_score=84),
    dict(sku="ELEC-004", niche="electronics", supplier="Sunrise Wholesale", warehouse_state="NJ",
         title="Mini Thermal Photo Printer — Inkless, Bluetooth",
         description="Pocket printer for stickers, labels and photos. Viral with journaling/student audiences.",
         cost=14.90, suggested_price=42.99, shipping_days_min=2, shipping_days_max=4, trending_score=86),
    dict(sku="ELEC-005", niche="electronics", supplier="US Direct Wholesale", warehouse_state="GA",
         title="Clip-On Selfie Ring Light — Rechargeable",
         description="3 light modes, USB-C. Cheap, light, evergreen content-creator accessory.",
         cost=3.10, suggested_price=16.99, shipping_days_min=3, shipping_days_max=6, trending_score=72),

    # ── Tools & Home Improvement ────────────────────────────────────────
    dict(sku="TOOL-001", niche="tools_home_improvement", supplier="Sunrise Wholesale", warehouse_state="CA",
         title="4V Cordless Electric Screwdriver Set — 47 Bits",
         description="USB-C rechargeable precision driver. Consistent top-50 in its Amazon subcategory.",
         cost=9.80, suggested_price=29.99, shipping_days_min=2, shipping_days_max=5, trending_score=83),
    dict(sku="TOOL-002", niche="tools_home_improvement", supplier="US Direct Wholesale", warehouse_state="TX",
         title="Laser Distance Measure — 165ft, Backlit LCD",
         description="Real-estate agents, contractors and DIYers. High perceived value, low return rate.",
         cost=16.20, suggested_price=44.99, shipping_days_min=2, shipping_days_max=5, trending_score=76),
    dict(sku="TOOL-003", niche="tools_home_improvement", supplier="Sunrise Wholesale", warehouse_state="NJ",
         title="Magnetic Wristband for Screws & Bits",
         description="15 magnets hold screws, nails, drill bits. Classic gift item — spikes Nov-Dec.",
         cost=2.40, suggested_price=14.99, shipping_days_min=2, shipping_days_max=5, trending_score=79),
    dict(sku="TOOL-004", niche="tools_home_improvement", supplier="US Direct Wholesale", warehouse_state="OH",
         title="Universal Socket Grip Tool — Self-Adjusting",
         description="Fits 1/4\"–3/4\" nuts and bolts. Gift-friendly, impulse-priced, steady seller.",
         cost=3.60, suggested_price=17.99, shipping_days_min=3, shipping_days_max=6, trending_score=70),
    dict(sku="TOOL-005", niche="tools_home_improvement", supplier="Sunrise Wholesale", warehouse_state="CA",
         title="LED Work Light — Rechargeable, Magnetic Base",
         description="360° swivel, 3 modes, COB LED. Mechanics + camping crossover appeal.",
         cost=7.30, suggested_price=26.99, shipping_days_min=2, shipping_days_max=5, trending_score=74),

    # ── Outdoor & Garden ────────────────────────────────────────────────
    dict(sku="OUTD-001", niche="outdoor_garden", supplier="Sunrise Wholesale", warehouse_state="CA",
         title="Solar-Powered Garden Lights — 8-Pack, Auto On/Off",
         description="Stainless pathway lights. Spring/summer volume monster, healthy margin.",
         cost=11.00, suggested_price=32.99, shipping_days_min=2, shipping_days_max=5, trending_score=85),
    dict(sku="OUTD-002", niche="outdoor_garden", supplier="GreenDropShip", warehouse_state="PA",
         title="Self-Watering Planter Set — Indoor Herb Kit",
         description="3-pot windowsill kit with wick system. Kitchen + gardening niche crossover.",
         cost=8.90, suggested_price=28.99, shipping_days_min=2, shipping_days_max=5, trending_score=68),
    dict(sku="OUTD-003", niche="outdoor_garden", supplier="US Direct Wholesale", warehouse_state="TX",
         title="Collapsible Camping Lantern — Solar + USB",
         description="Doubles as a phone charger. Prepper + camping + emergency-kit audiences.",
         cost=5.70, suggested_price=21.99, shipping_days_min=3, shipping_days_max=6, trending_score=81),
    dict(sku="OUTD-004", niche="outdoor_garden", supplier="Sunrise Wholesale", warehouse_state="CA",
         title="Heavy-Duty Garden Kneeler & Seat — Foldable",
         description="EVA pad + tool pouch. Older-buyer demographic — converts well on Facebook ads.",
         cost=13.40, suggested_price=39.99, shipping_days_min=2, shipping_days_max=5, trending_score=77),
    dict(sku="OUTD-005", niche="outdoor_garden", supplier="US Direct Wholesale", warehouse_state="FL",
         title="Wind-Resistant Patio Umbrella Base — 50lb",
         description="Fillable base fits most poles. Seasonal but high ticket with low competition.",
         cost=19.80, suggested_price=54.99, shipping_days_min=3, shipping_days_max=7, trending_score=62),

    # ── Toys & Games ────────────────────────────────────────────────────
    dict(sku="TOY-001", niche="toys_games", supplier="BryBelly", warehouse_state="IN",
         title="Magnetic Building Tiles — 64pc Set",
         description="STEM construction tiles, ages 3+. Top-gifted toy category, low breakage returns.",
         cost=14.20, suggested_price=39.99, shipping_days_min=2, shipping_days_max=5, trending_score=89),
    dict(sku="TOY-002", niche="toys_games", supplier="BryBelly", warehouse_state="IN",
         title="LED Flying Orb Ball — Boomerang Spinner",
         description="Rechargeable hover toy. Massive holiday spikes — stock it before Q4.",
         cost=6.80, suggested_price=24.99, shipping_days_min=2, shipping_days_max=5, trending_score=87),
    dict(sku="TOY-003", niche="toys_games", supplier="BryBelly", warehouse_state="IN",
         title="Wooden Puzzle Brain Teasers — 6-Pack",
         description="Adult + kid gift crossover. Light, unbreakable, high review velocity.",
         cost=7.50, suggested_price=25.99, shipping_days_min=2, shipping_days_max=5, trending_score=66),
    dict(sku="TOY-004", niche="toys_games", supplier="US Direct Wholesale", warehouse_state="NJ",
         title="LCD Writing Tablet for Kids — 10in",
         description="Doodle board, erase button, stylus. Cheap gift staple with year-round demand.",
         cost=5.20, suggested_price=19.99, shipping_days_min=3, shipping_days_max=6, trending_score=73),

    # ── Kitchen & Dining ────────────────────────────────────────────────
    dict(sku="KIT-001", niche="kitchen_dining", supplier="Sunrise Wholesale", warehouse_state="CA",
         title="Electric Milk Frother — Handheld, USB Recharge",
         description="Coffee-tok staple. Cheap to ship, reviewers love it, cross-sells with mugs.",
         cost=4.10, suggested_price=19.99, shipping_days_min=2, shipping_days_max=5, trending_score=82),
    dict(sku="KIT-002", niche="kitchen_dining", supplier="GreenDropShip", warehouse_state="PA",
         title="Vegetable Chopper — 12-in-1 Mandoline Set",
         description="The 'TikTok chopper' category is still hot. Container catches, 7 blades.",
         cost=9.40, suggested_price=31.99, shipping_days_min=2, shipping_days_max=5, trending_score=90),
    dict(sku="KIT-003", niche="kitchen_dining", supplier="Sunrise Wholesale", warehouse_state="NJ",
         title="Silicone Air Fryer Liner Set — Reusable",
         description="Fits 5-8qt fryers, 2-pack. Air-fryer accessory demand keeps compounding.",
         cost=3.30, suggested_price=15.99, shipping_days_min=2, shipping_days_max=5, trending_score=78),
    dict(sku="KIT-004", niche="kitchen_dining", supplier="US Direct Wholesale", warehouse_state="GA",
         title="Magnetic Spice Jars — 12pc with Labels",
         description="Fridge/RV-mount spice storage. Organization niche, strong Pinterest traffic.",
         cost=10.60, suggested_price=33.99, shipping_days_min=3, shipping_days_max=6, trending_score=71),
    dict(sku="KIT-005", niche="kitchen_dining", supplier="Sunrise Wholesale", warehouse_state="CA",
         title="Portable Blender — USB-C, 13oz Personal Size",
         description="Smoothies anywhere — gym, office, travel. High AOV with color variants.",
         cost=8.80, suggested_price=29.99, shipping_days_min=2, shipping_days_max=5, trending_score=84),

    # ── Sports & Fitness ────────────────────────────────────────────────
    dict(sku="FIT-001", niche="sports_fitness", supplier="Sunrise Wholesale", warehouse_state="CA",
         title="Adjustable Weighted Jump Rope — Ball Bearing",
         description="Cable speed rope with weighted handles. Cheap shipping, evergreen fitness staple.",
         cost=4.60, suggested_price=21.99, shipping_days_min=2, shipping_days_max=5, trending_score=75),
    dict(sku="FIT-002", niche="sports_fitness", supplier="US Direct Wholesale", warehouse_state="TX",
         title="Resistance Band Set — 5 Levels + Door Anchor",
         description="Home-gym entry product. Bundle with ankle straps for +$10 AOV.",
         cost=6.90, suggested_price=26.99, shipping_days_min=2, shipping_days_max=5, trending_score=80),
    dict(sku="FIT-003", niche="sports_fitness", supplier="Sunrise Wholesale", warehouse_state="CA",
         title="Posture Corrector — Adjustable Back Brace",
         description="Desk-worker pain-point product. Big ad-tested angles: WFH, students, drivers.",
         cost=5.10, suggested_price=22.99, shipping_days_min=2, shipping_days_max=5, trending_score=83),
    dict(sku="FIT-004", niche="sports_fitness", supplier="US Direct Wholesale", warehouse_state="FL",
         title="Insulated Gym Water Bottle — 40oz, Straw Lid",
         description="Powder-coated stainless, boot included. Riding the Stanley/Owala wave.",
         cost=7.90, suggested_price=27.99, shipping_days_min=3, shipping_days_max=6, trending_score=79),
    dict(sku="FIT-005", niche="sports_fitness", supplier="Sunrise Wholesale", warehouse_state="NJ",
         title="Massage Gun — 6 Heads, Quiet Motor",
         description="Recovery category keeps growing. Mid-ticket with strong gift appeal.",
         cost=18.50, suggested_price=49.99, shipping_days_min=2, shipping_days_max=4, trending_score=81),

    # ── Beauty & Personal Care ──────────────────────────────────────────
    dict(sku="BEAU-001", niche="beauty_personal_care", supplier="GreenDropShip", warehouse_state="PA",
         title="Jade Roller & Gua Sha Facial Set",
         description="Natural stone set in gift box. Consistent seller, tiny package, cheap to ship.",
         cost=3.80, suggested_price=18.99, shipping_days_min=2, shipping_days_max=5, trending_score=70),
    dict(sku="BEAU-002", niche="beauty_personal_care", supplier="Sunrise Wholesale", warehouse_state="CA",
         title="Heatless Curling Rod Set — Silk",
         description="Overnight curls, no heat damage — huge TikTok history, still sells steady.",
         cost=3.40, suggested_price=16.99, shipping_days_min=2, shipping_days_max=5, trending_score=76),
    dict(sku="BEAU-003", niche="beauty_personal_care", supplier="GreenDropShip", warehouse_state="PA",
         title="Ionic Hair Dryer Brush — One-Step Volumizer",
         description="Salon-style blowout tool. Higher ticket, strong gifting season performance.",
         cost=15.80, suggested_price=44.99, shipping_days_min=2, shipping_days_max=5, trending_score=85),
    dict(sku="BEAU-004", niche="beauty_personal_care", supplier="Sunrise Wholesale", warehouse_state="CA",
         title="LED Makeup Mirror — Tri-Fold, 21 LEDs",
         description="Touch dimming, 1x/2x/3x magnification. Vanity upgrade gift for teens + adults.",
         cost=8.10, suggested_price=28.99, shipping_days_min=2, shipping_days_max=5, trending_score=72),
    dict(sku="BEAU-005", niche="beauty_personal_care", supplier="GreenDropShip", warehouse_state="PA",
         title="Organic Beard Grooming Kit — Oil, Balm, Brush",
         description="Men's grooming gift set, natural ingredients. Father's Day + holiday spikes.",
         cost=9.20, suggested_price=32.99, shipping_days_min=2, shipping_days_max=5, trending_score=74),

    # ── Baby & Nursery ──────────────────────────────────────────────────
    dict(sku="BABY-001", niche="baby_nursery", supplier="Sunrise Wholesale", warehouse_state="CA",
         title="Baby Stroller Fan — Clip-On, Flexible Tripod",
         description="Octopus-leg fan, quiet brushless motor. Summer demand + year-round travel use.",
         cost=6.20, suggested_price=22.99, shipping_days_min=2, shipping_days_max=5, trending_score=82),
    dict(sku="BABY-002", niche="baby_nursery", supplier="US Direct Wholesale", warehouse_state="TX",
         title="Portable White Noise Machine — Baby Sleep",
         description="20 sounds, night light, rechargeable. New-parent essential, great reviews.",
         cost=9.70, suggested_price=29.99, shipping_days_min=3, shipping_days_max=6, trending_score=86),
    dict(sku="BABY-003", niche="baby_nursery", supplier="Sunrise Wholesale", warehouse_state="NJ",
         title="Diaper Bag Organizer Insert — 8 Pockets",
         description="Turns any tote into a diaper bag. Budget angle resonates — cheap AOV builder.",
         cost=5.50, suggested_price=19.99, shipping_days_min=2, shipping_days_max=5, trending_score=64),
    dict(sku="BABY-004", niche="baby_nursery", supplier="US Direct Wholesale", warehouse_state="GA",
         title="Silicone Baby Feeding Set — Suction Plate + Bib",
         description="BPA-free, dishwasher safe, gift-boxed. Registry-style gift buyers pay premium.",
         cost=8.40, suggested_price=29.99, shipping_days_min=3, shipping_days_max=6, trending_score=78),

    # ── Pet Supplies ────────────────────────────────────────────────────
    dict(sku="PET-001", niche="pet_supplies", supplier="Pet Stores USA", warehouse_state="OH",
         title="Rechargeable LED Dog Collar — USB",
         description="Night-walk safety collar, cut-to-size TPU. Pet owners spend on safety — strong margin.",
         cost=4.90, suggested_price=21.99, shipping_days_min=2, shipping_days_max=5, trending_score=88),
    dict(sku="PET-002", niche="pet_supplies", supplier="Pet Stores USA", warehouse_state="OH",
         title="Cat Water Fountain — 2.4L, Quiet Pump",
         description="Circulating filtered water — vets recommend, subscription-filter upsell exists.",
         cost=11.30, suggested_price=34.99, shipping_days_min=2, shipping_days_max=5, trending_score=90),
    dict(sku="PET-003", niche="pet_supplies", supplier="Pet Stores USA", warehouse_state="TX",
         title="Dog Seat Belt + Car Harness Set",
         description="Crash-tested style harness. Safety angle converts; low return rate.",
         cost=5.80, suggested_price=19.99, shipping_days_min=2, shipping_days_max=5, trending_score=71),
    dict(sku="PET-004", niche="pet_supplies", supplier="Pet Stores USA", warehouse_state="OH",
         title="Self-Cleaning Slicker Brush — Retractable",
         description="One-click hair release. The 'de-shedding' category is huge and loyal.",
         cost=3.90, suggested_price=17.99, shipping_days_min=2, shipping_days_max=5, trending_score=79),
    dict(sku="PET-005", niche="pet_supplies", supplier="Pet Stores USA", warehouse_state="TX",
         title="Snuffle Mat — Slow-Feed Enrichment Puzzle",
         description="Mental-stimulation feeding mat — vet-behaviorist endorsed category, low competition.",
         cost=7.60, suggested_price=25.99, shipping_days_min=2, shipping_days_max=5, trending_score=83),

    # ── Video Games ─────────────────────────────────────────────────────
    dict(sku="GAME-001", niche="video_games", supplier="Sunrise Wholesale", warehouse_state="CA",
         title="RGB Gaming Headset Stand — USB Hub",
         description="Headphone stand + 2-port USB + RGB. Accessory attach-rate products sell.",
         cost=8.60, suggested_price=29.99, shipping_days_min=2, shipping_days_max=5, trending_score=74),
    dict(sku="GAME-002", niche="video_games", supplier="US Direct Wholesale", warehouse_state="TX",
         title="Controller Thumb Grip Caps — 20pc Set",
         description="Fit PS5/Xbox/Switch. Ultra-cheap, add-on item that pads margins on any order.",
         cost=1.80, suggested_price=11.99, shipping_days_min=3, shipping_days_max=6, trending_score=69),
    dict(sku="GAME-003", niche="video_games", supplier="Sunrise Wholesale", warehouse_state="NJ",
         title="Retro Handheld Console — 400 Built-in Games",
         description="Nostalgia-driven impulse buy; big holiday traffic every year.",
         cost=12.90, suggested_price=36.99, shipping_days_min=2, shipping_days_max=5, trending_score=80),
    dict(sku="GAME-004", niche="video_games", supplier="US Direct Wholesale", warehouse_state="CA",
         title="Cable Management Sleeve Kit — Gaming Desk",
         description="4 neoprene sleeves + clips. Desk-setup niche overlaps tech + home org.",
         cost=4.20, suggested_price=18.99, shipping_days_min=3, shipping_days_max=6, trending_score=63),
]
